### Ollama status
GET http://localhost:11434/

### List all installed models
GET http://localhost:11434/api/tags

### Download a model
POST http://localhost:11434/api/pull

{
    "model": "gemma:latest"
}
